service:
  replicas: 2
  readiness_probe: /v1/models

envs:
  BUCKET_NAME:

resources:
  accelerators: L4:1
  ports: 9000
  cpus: 8+
  memory: 16+

file_mounts:
  /artifacts:
    name: $BUCKET_NAME
    store: gcs

setup: pip install vllm==0.6.2

run: |
  vllm serve /artifacts/skychat \
    --host 0.0.0.0 --port 9000 \
    --served-model-name skychat
